### ISSUE TITLE
About clash_flt2

### ISSUE THREAD

**Issue by hiFrankYoung** [LondonX/clash_flt#16]
Hello, 
I'm very interesting in it, also i can write some code, maybe golang, java, flutter etc.
I want to study more about it.

**Comment by dollar-cat** [comment]
针的嘛 目前安卓 在android9下 连接vpn无网络传输 作者说可能是tun2socks问题 你能处理一下嘛

**Comment by LondonX** [comment]
@dollar-cat 原版fclash的编译脚本里有一个带tun模式的编译方法，我还没时间看，可能fclash的作者已经把更好的tun集成进core里了？

@hiFrankYoung That's awesome! An collaborating invitation has been sent to you, if you willing to help with anything, apply and join us. Just don't mess up with `master` branch lol

**Comment by hiFrankYoung** [comment]
> @dollar-cat 原版fclash的编译脚本里有一个带tun模式的编译方法，我还没时间看，可能fclash的作者已经把更好的tun集成进core里了？
> 
> 
> 
> @hiFrankYoung That's awesome! An collaborating invitation has been sent to you, if you willing to help with anything, apply and join us. Just don't mess up with `master` branch lol

Thanks very much.I need do some research about it.

**Comment by hiFrankYoung** [comment]
@LondonX Check this

https://github.com/trojan-gfw/igniter-go-libs/tree/master

**Comment by LondonX** [comment]
@hiFrankYoung The igniter appears to be outdated. I might think about switching to https://github.com/eycorsican/leaf instead. Leaf also provides prebuilt binary files on its release page, which could save a significant amount of time when setting up a Rust environment.

**Comment by FaceTheWorld233** [comment]
Hi, I can't implement certain functions due to the existing clash version is too low, I heard that clash_flt2 has upgraded this part, so I am very interested in clash_flt2, can you invite me to join the project? Thank you very much.

**Comment by dollar-cat** [comment]
clash_flt2依然存在一些问题 等作者有时间修复好 会公开的

**Comment by dollar-cat** [comment]
> 好，由于现有的clash版本太低，我无法实现某些功能，听说clash_flt2已经升级了这部分，所以我对clash_flt2很感兴趣，你能邀请我加入这个项目吗？非常感谢。

clash_flt2仍然存在一些问题 等作者有时间修复好 会公开的

**Comment by bahram333** [comment]
你好
可以邀请我加入 crash_flt2 项目吗？

Hello
Is it possible to invite me to the clash_flt2 project?

**Comment by liuzhebaba** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
lovebingo, @user883311, @JingweiWang, @RajeshNaddy, @Pablohn26, @mrteax, @EingShaw, @kirobo, @Adward-R, @aytee17, @terappy, @albertmiro, @yizhoumo, @borisdamato, @Nguyen893, @stormzhang, @GOVINDDIXIT, @huangdroid, @chaishuanzhu, @kotaoching

**Comment by LondonX** [comment]
[clash_flt2](https://github.com/LondonX/clash_flt2)现已开源，欢迎PR
